export const MATCH_DATA = [
    {
        id: "0",
        team1: "Al-Hilal",
        team2: "Al-Nassr",
        league: "Ərəb Klublar çempionatı",
        match_date: "2023-08-12",
        rating: 8.7,
        raund: "Final",
        score: "1 - 2",
        homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/optimized/44LCSbthsfHKW9YOATA18A_64x64.png",
        awayLogo: "https://media.api-sports.io/football/teams/2939.png",
        homeBg: "#0000ff",
        awayBg: "#fedc00",
        possesions: { home: 56, away: 44, home_percent: 56, away_percent: 44 },
        shoots: { home: 20, away: 19, home_percent: 51.2, away_percent: 48.8 },
        shoots_on_target: { home: 4, away: 10, home_percent: 28.5, away_percent: 71.5 },
        pass: { home: 383, away: 292, home_percent: 60.5, away_percent: 39.5 },
        offside: { home: 5, away: 12, home_percent: 26.3, away_percent: 73.7 },
        goals: [
            { minute: 51, player: "Michael", team: "home" },
            { minute: 74, player: "Cristiano Ronaldo", team: "away" },
            { minute: 98, player: "Cristiano Ronaldo", team: "away" }
        ]
    },
    {
        id: "1",
        team1: "Qarabağ",
        team2: "Frankfurt",
        league: "UEFA Çempionlar liqası",
        match_date: "2026-01-21",
        rating: 9.8,
        raund: "Qrup mərhələsi",
        score: "3 - 2",
        homeLogo: "https://upload.wikimedia.org/wikipedia/az/1/13/Qaraba%C4%9F_FK_loqo.png?utm_source=az.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Eintracht_Frankfurt_crest.svg/1280px-Eintracht_Frankfurt_crest.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
        homeBg: "#1c0f59",
        awayBg: "#e1020c",
        possesions: { home: 59, away: 41, home_percent: 59, away_percent: 41 },
        shoots: { home: 10, away: 6, home_percent: 62.5, away_percent: 37.5 },
        shoots_on_target: { home: 6, away: 5, home_percent: 54.5, away_percent: 45.5 },
        pass: { home: 521, away: 340, home_percent: 60.5, away_percent: 39.5 },
        offside: { home: 1, away: 0, home_percent: 100, away_percent: 0 },
        goals: [
            { minute: 4, player: "Camilo Durán", team: "home" },
            { minute: 10, player: "Can Uzun", team: "away" },
            { minute: 78, player: "Farès Chaïbi (P)", team: "away" },
            { minute: 80, player: "Camilo Durán", team: "home" },
            { minute: "90+4", player: "Bəhlul Mustafazadə", team: "home" }
        ]
    },
    {
        id: "2",
        team1: "Portuqaliya",
        team2: "Xorvatiya",
        league: "Dünya Çempionatı",
        match_date: "2026-07-03",
        rating: 9,
        raund: "Son 32",
        score: "2 - 1",
        homeLogo: "https://upload.wikimedia.org/wikipedia/tr/8/8f/100px-Portugal_FPF_crest.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/tr/c/cf/Croatia_football_federation.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        homeBg: "#d43528",
        awayBg: "#ffffff",
        possesions: { home: 62, away: 38, home_percent: 62, away_percent: 38 },
        shoots: { home: 15, away: 13, home_percent: 53.5, away_percent: 46.5 },
        shoots_on_target: { home: 3, away: 7, home_percent: 30, away_percent: 70 },
        pass: { home: 542, away: 384, home_percent: 58.5, away_percent: 41.5 },
        offside: { home: 1, away: 4, home_percent: 20, away_percent: 80 },
        goals: [
            { minute: 53, player: "Ivan Perišić", team: "away" },
            { minute: 68, player: "Cristiano Ronaldo (P)", team: "home" },
            { minute: "90+4", player: "Gonçalo Ramos", team: "home" }
        ]
    },
    {
        id: "3",
        team1: "Real Madrid",
        team2: "Man City",
        league: "UEFA Çempionlar liqası",
        match_date: "2026-03-12",
        rating: 8.8,
        raund: "Son 16",
        score: "3 - 0",
        homeLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/960px-Real_Madrid_CF.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
        awayLogo: "https://upload.wikimedia.org/wikipedia/tr/f/f6/Manchester_City.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        homeBg: "#f7fafc",
        awayBg: "#6caddf",
        possesions: { home: 42, away: 58, home_percent: 42, away_percent: 58 },
        shoots: { home: 11, away: 9, home_percent: 55, away_percent: 45 },
        shoots_on_target: { home: 7, away: 5, home_percent: 58.3, away_percent: 41.7 },
        pass: { home: 368, away: 556, home_percent: 60.1, away_percent: 39.9 },
        offside: { home: 1, away: 0, home_percent: 100, away_percent: 0 },
        goals: [
            { minute: 20, player: "Federico Valverde", team: "home" },
            { minute: 27, player: "Federico Valverde", team: "home" },
            { minute: 42, player: "Federico Valverde", team: "home" }
        ]
    },
    {
        id: "4",
        team1: "Portuqaliya",
        team2: "İspaniya",
        league: "UEFA Millətlər liqası",
        match_date: "2025-06-08",
        rating: 9.8,
        raund: "Final",
        score: "2 - 2",
        penalties: "5-3",
        homeLogo: "https://upload.wikimedia.org/wikipedia/tr/8/8f/100px-Portugal_FPF_crest.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Spain_national_football_team_crest.svg/960px-Spain_national_football_team_crest.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
        homeBg: "#d43528",
        awayBg: "#ffc808",
        possesions: { home: 40, away: 60, home_percent: 40, away_percent: 60 },
        shoots: { home: 9, away: 16, home_percent: 36, away_percent: 64 },
        shoots_on_target: { home: 5, away: 6, home_percent: 45, away_percent: 55 },
        pass: { home: 445, away: 760, home_percent: 63.1, away_percent: 36.9 },
        offside: { home: 4, away: 3, home_percent: 57.1, away_percent: 42.9 },
        goals: [
            { minute: 21, player: "Martín Zubimendi", team: "away" },
            { minute: 26, player: "Nuno Mendes", team: "home" },
            { minute: 45, player: "Mikel Oyarzabal", team: "away" },
            { minute: 61, player: "Cristiano Ronaldo", team: "home" }
        ]
    },
    {
        id: "5",
        team1: "Chelsea",
        team2: "Hull City",
        league: "Premier league",
        match_date: "2026-09-12",
        rating: 8.5,
        raund: "Liqa",
        score: "2 - 2",
        homeLogo: "https://thumb.wikimedia.org/wikipedia/tr/thumb/0/0d/Chelsea_FC.png/250px-Chelsea_FC.png?utm_source=tr.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
        awayLogo: "https://img.a.transfermarkt.technology/wappen/head/3008.png?lm=4711",
        homeBg: "#000c8a",
        awayBg: "#ed8b02",
        possesions: { home: 68, away: 32, home_percent: 68, away_percent: 32 },
        shoots: { home: 13, away: 13, home_percent: 50, away_percent: 50 },
        shoots_on_target: { home: 8, away: 6, home_percent: 57.1, away_percent: 42.9 },
        pass: { home: 542, away: 267, home_percent: 67, away_percent: 33 },
        offside: { home: 1, away: 1, home_percent: 50, away_percent: 50 },
        goals: [
            { minute: 7, player: "Morgan Rogers", team: "home" },
            { minute: 28, player: "Muhammed Bellumi", team: "away" },
            { minute: 34, player: "Muhammed Bellumi", team: "away" },
            { minute: 66, player: "João Pedro", team: "home" }
        ],

        lineups: {
            home: [
                "Emiliano Martínez",
                "Wesley Fofana",
                "Levi Colwill",
                "Jorrel Hato",
                "Pedro Neto",
                "Reece James",
                "Roméo Lavia",
                "Malo Gusto",
                "Cole Palmer",
                "Morgan Rogers",
                "João Pedro"
            ],
            away: [
                "Konstantinos Tzolakis",
                "Lewie Coyle",
                "Semi Ajayi",
                "John Egan",
                "Nobel Mendy",
                "Ryan Giles",
                "Mohamed Belloumi",
                "Matt Crooks",
                "Regan Slater",
                "Elliot Stroud",
                "Oliver McBurnie"
            ]
        },

        substitutes: {
            home: [
                "Mike Penders",
                "Valentín Barco",
                "Maxence Lacroix",
                "Jamie Gittens",
                "Danny Welbeck",
                "Geovany Quenda",
                "Pep Chavarría",
                "Josh Acheampong",
                "Estêvão"
            ],
            away: [
                "Dillon Phillips",
                "Sorba Thomas",
                "Brooke Norton-Cuffy",
                "Lucas Herrington",
                "Matt Targett",
                "Lucas Gourna-Douath",
                "Tim Iroegbunam",
                "Robinio Vaz",
                "Mohamed-Ali Cho"
            ]
        },
    },
];