export const MATCH_DATA = [
    {
        id: "0",
        team1: "Al-Hilal",
        team2: "Al-Nassr",
        league: "Ərəb Klublar çempionatı",
        match_date: "2023-08-12",
        rating: 8.7,
        raund:"Final",
        score: "1 - 2",
        homeLogo: "https://ssl.gstatic.com/onebox/media/sports/logos/optimized/44LCSbthsfHKW9YOATA18A_64x64.png",
        awayLogo: "https://media.api-sports.io/football/teams/2939.png",
    },
     {
        id: "1",
        team1: "Qarabağ",
        team2: "Frankfurt",
        league: "UEFA Çempionlar liqası",
        match_date: "2026-01-21",
        rating: 9.8,
        raund:"Qrup mərhələsi",
        score: "3 - 2",
        homeLogo: "https://upload.wikimedia.org/wikipedia/az/1/13/Qaraba%C4%9F_FK_loqo.png?utm_source=az.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Eintracht_Frankfurt_crest.svg/1280px-Eintracht_Frankfurt_crest.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
    },
     {
        id: "2",
        team1: "Portuqaliya",
        team2: "Xorvatiya",
        league: "Dünya Çempionatı",
        match_date: "2026-07-03",
        rating: 9,
        raund:"Son 32",
        score: "2 - 1",
        homeLogo: "https://upload.wikimedia.org/wikipedia/tr/8/8f/100px-Portugal_FPF_crest.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/tr/c/cf/Croatia_football_federation.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
    },
     {
        id: "3",
        team1: "Real Madrid",
        team2: "Man City",
        league: "UEFA Çempionlar liqası",
        match_date: "2026-03-12",
        rating: 8.8,
        raund:"Son 16",
        score: "3 - 0",
        homeLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/960px-Real_Madrid_CF.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
        awayLogo: "https://upload.wikimedia.org/wikipedia/tr/f/f6/Manchester_City.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
    },
    {
        id: "4",
        team1: "Portuqaliya",
        team2: "İspaniya",
        league: "UEFA Millətlər liqası",
        match_date: "2025-06-08",
        rating: 9.8,
        raund:"Final",
        score: "2 - 2",
        penalties:"5-3",
        homeLogo: "https://upload.wikimedia.org/wikipedia/tr/8/8f/100px-Portugal_FPF_crest.png?utm_source=tr.wikipedia.org&utm_campaign=index&utm_content=original",
        awayLogo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Spain_national_football_team_crest.svg/960px-Spain_national_football_team_crest.svg.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=thumbnail",
    },
];